export const bgmDict = [
  { "name": "설렘, 가벼운 휘파람 곡", "file_name": "bgm_joy_whistle.mp3" },
  { "name": "긴박/긴장 빠른 비트 1", "file_name": "bgm_alert_rush.mp3" },
  { "name": "긴박/긴장 빠른 비트 2", "file_name": "bgm_alert_rush2.mp3" },
  { "name": "위기 빠른 비트", "file_name": "bgm_crisis_edmrush.mp3" },
  { "name": "기쁨, 팡파레, 경쾌함", "file_name": "bgm_happy_fanfare.mp3" },
  { "name": "케이팝", "file_name": "d_kpop.mp3" },
  { "name": "릴렉싱", "file_name": "d_relaxing.mp3" },
  { "name": "세련됨", "file_name": "d_fancy.mp3" },
  { "name": "경쾌", "file_name": "d_joyful.mp3" },
  { "name": "어린이", "file_name": "d_childish.mp3" },
  { "name": "야경/신디", "file_name": "d_nightview.mp3" },
  { "name": "상쾌한 아침 출발용 브라스 밴드", "file_name": "d_morning_band.mp3" },
  { "name": "로파이 힙합(감성/힐링용)", "file_name": "d_healing_hiphop.mp3" },
  { "name": "설렘 가득 인디팝", "file_name": "d_indipop.mp3" },
  { "name": "클래식(스트링/피아노)", "file_name": "d_classic.mp3" },
  { "name": "잔잔한 재즈 피아노", "file_name": "d_jazzpiano.mp3" },
  { "name": "어쿠스틱 기타 곡", "file_name": "d_acoustic_guitar.mp3" }
];

export const bgvDict = [
  { "description": "해안도로(노을)", "file_name": "bg_coastsunset_day.mp4" },
  { "description": "해안도로(낮)", "file_name": "bg_coastalroaday.mp4" },
  { "description": "폭우 도로(밤)", "file_name": "bg_heavyrain_night.mp4" },
  { "description": "편의점 앞(밤)", "file_name": "bg_conveniencestore_night.mp4" },
  { "description": "택배 허브 물류센터 진입(낮)", "file_name": "bg_logisticshubentry_day.mp4" },
  { "description": "택배 픽업(밤)", "file_name": "bg_parcelpickup_night.mp4" },
  { "description": "택배 픽업(낮)", "file_name": "bg_parcelpickup_day.mp4" },
  { "description": "쇼핑몰(낮)", "file_name": "bg_shoppingmall_day.mp4" },
  { "description": "새벽도로(밤)", "file_name": "bg_dawndimroad_night.mp4" },
  { "description": "반려동물 놀이터(낮)", "file_name": "bg_petparkentry_day.mp4" },
  { "description": "바닷가 마을(낮)", "file_name": "bg_seasidevillage_day.mp4" },
  { "description": "드라이브 스루 마트(낮)", "file_name": "bg_drivethrumarket_day.mp4" },
  { "description": "단풍길(낮)", "file_name": "bg_autumnleaf_day.mp4" },
  { "description": "다리 위 야경(밤)", "file_name": "bg_citybridge_night.mp4" },
  { "description": "교통체증(낮)", "file_name": "bg_trafficjam_day.mp4" },
  { "description": "공항(낮)", "file_name": "bg_airport_day.mp4" },
  { "description": "고속도로 진입ic(낮)", "file_name": "bg_highwayentry_day.mp4" },
  { "description": "고속도로 주행(낮)", "file_name": "bg_highwaydrive_day.mp4" },
  { "description": "갯마을(낮)", "file_name": "bg_foreshore_day.mp4" },
  { "description": "자동세차장(낮)", "file_name": "bg_carwash_day1.mp4" },
  { "description": "힐링 풍경2", "file_name": "bg_healinglandscape2_day.mp4" },
  { "description": "힐링 풍경1", "file_name": "bg_healinglandscape1_day.mp4" },
  { "description": "하늘에서 젤리곰이 떨어져1", "file_name": "bg_fallingjellybear1_surreal.mp4" },
  { "description": "풍선을 타고 날아다님", "file_name": "bg_floatingballoons_surreal.mp4" },
  { "description": "초현실 세상(지브리풍 도시)", "file_name": "bg_ghiblicity_surreal.mp4" },
  { "description": "음료가 되서 보는 세상", "file_name": "bg_colorfuldrink_surreal.mp4" },
  { "description": "시골길(낮)", "file_name": "bg_countryroad_night.mp4" },
  { "description": "사탕으로 만들어진 세상2", "file_name": "bg_candywonderland2_surreal.mp4" },
  { "description": "공룡 정글 2", "file_name": "bg_jurassicjungle2_surreal.mp4" },
]