//rebuild_19.5
export const bgmDict = [
  { "title": "긴장/위기 빠른 비트", "file_name": "bgm_crisis_edmrush.mp3", "tags": ["긴장", "위기", "빠른 비트"] },
  { "title": "제로원 빌더 ver.1", "file_name": "bgm_ending_zerobuilder_v1.mp3", "tags": ["엔딩", "희망", "여행", "에너지"] },
  { "title": "제로원 빌더 original", "file_name": "bgm_ending_zerobuilder_v2.mp3", "tags": ["엔딩", "희망", "진정성", "따뜻함"] },
  { "title": "기쁨, 팡파레, 경쾌함", "file_name": "bgm_happy_fanfare.mp3", "tags": ["기쁨", "팡파레", "경쾌"] },
  { "title": "설렘2 가벼운 휘파람 곡", "file_name": "bgm_joy_whistle.mp3", "tags": ["설렘", "휘파람", "경쾌"] },
  { "title": "벅차오르는 음악(cinematic music)", "file_name": "cinematicmusic_bright.mp3", "tags": ["희망", "에너지", "감동", "시네마틱"] },
  { "title": "기분전환(일이 안 풀릴때 자기 위로)1", "file_name": "conversion_borntobreak1.mp3", "tags": ["기분전환", "자기위로", "회복"] },
  { "title": "기분전환(일이 안 풀릴때 자기 위로)2", "file_name": "conversion_borntobreak2.mp3", "tags": ["기분전환", "자기위로", "회복"] },
  { "title": "설렘1", "file_name": "date_romanticfanfare.mp3", "tags": ["설렘", "로맨틱", "밝음"] },
  { "title": "경쾌", "file_name": "doori_dance.mp3", "tags": ["댄스", "경쾌", "신남"] },
  { "title": "바다 드라이브(탁 트인 바다)", "file_name": "drivetothesea_elecguitar1.mp3", "tags": ["바다", "여행", "청량", "에너지"] },
  { "title": "바다로 떠날 때(박수 치는 경쾌함)", "file_name": "drivetothesea_rock2.mp3", "tags": ["바다", "출발", "경쾌", "밝음"] },
  { "title": "감성, 차분함1", "file_name": "emotion_moodypiano.mp3", "tags": ["감성", "차분함", "잔잔함"] },
  { "title": "감성, 차분함2", "file_name": "emotion_rhythmicaldrum.mp3", "tags": ["감성", "차분함", "드럼"] },
  { "title": "즐거운 나들이(기타)", "file_name": "happydrivewifclone_guitar.mp3", "tags": ["즐거움", "여행", "기타"] },
  { "title": "즐거운 나들이(피아노)", "file_name": "happydrivewifclone_piano.mp3", "tags": ["즐거움", "여행", "피아노"] },
  { "title": "치유, 명상1", "file_name": "healing_calmpiano1.mp3", "tags": ["치유", "명상", "피아노", "잔잔함"] },
  { "title": "치유, 명상2", "file_name": "healing_calmpiano2.mp3", "tags": ["치유", "명상", "피아노", "잔잔함"] },
  { "title": "케이팝(케이팝 엔젤가디언)", "file_name": "kpop_cidarpop.mp3", "tags": ["케이팝", "트렌디", "밝음"] },
  { "title": "케이팝(로맨틱)", "file_name": "kpop_witu.mp3", "tags": ["케이팝", "로맨틱", "설렘"] },
  { "title": "세련된 도심 드라이브 음악1", "file_name": "nightdrive1.mp3", "tags": ["도심", "세련됨", "야경"] },
  { "title": "세련된 도심 드라이브 음악2", "file_name": "nightdrive2.mp3", "tags": ["도심", "세련됨", "야경"] },
  { "title": "엔딩, 기대, 설렘(클론21g와 즐거운 여행)", "file_name": "ourjourneytogether_guitar.mp3", "tags": ["엔딩", "기대", "설렘", "여행"] },
  { "title": "기대, 설렘", "file_name": "ourjourneytogether_whistle.mp3", "tags": ["설렘", "여행", "휘파람"] },
  { "title": "팝(리드미컬)2", "file_name": "pop_equationofme.mp3", "tags": ["팝", "리드미컬", "에너지"] },
  { "title": "팝(신남)", "file_name": "pop_letsgout.mp3", "tags": ["팝", "신남", "즐거움"] },
  { "title": "팝(리드미컬)1", "file_name": "pop_rhythmicpop.mp3", "tags": ["팝", "리드미컬", "밝음"] },
  { "title": "팝(신디팝)", "file_name": "pop_trendy.mp3", "tags": ["팝", "신디", "트렌디"] },
  { "title": "팝(chill pop)", "file_name": "pop_chill.mp3", "tags": ["팝", "칠", "여유"] },
];

export const bgvDict = [
  { "description": "해안도로(노을)", "file_name": "bg_coastsunset_day.mp4" },
  { "description": "해안도로(낮)", "file_name": "bg_coastalroaday.mp4" },
  { "description": "폭우 도로(밤)", "file_name": "bg_heavyrain_night.mp4" },
  { "description": "편의점 앞(밤)", "file_name": "bg_conveniencestore_night.mp4" },
  { "description": "택배 허브 물류센터 진입(낮)", "file_name": "bg_logisticshubentry_day.mp4" },
  { "description": "택배 픽업(밤)", "file_name": "bg_parcelpickup_night.mp4" },
  { "description": "택배 픽업(낮)", "file_name": "bg_parcelpickup_day.mp4" },
  { "description": "쇼핑몰(낮)", "file_name": "bg_shoppingmall_day.mp4" },
  { "description": "새벽도로(밤)", "file_name": "bg_dawndimroad_night.mp4" },
  { "description": "반려동물 놀이터(낮)", "file_name": "bg_petparkentry_day.mp4" },
  { "description": "바닷가 마을(낮)", "file_name": "bg_seasidevillage_day.mp4" },
  { "description": "드라이브 스루 마트(낮)", "file_name": "bg_drivethrumarket_day.mp4" },
  { "description": "단풍길(낮)", "file_name": "bg_autumnleaf_day.mp4" },
  { "description": "다리 위 야경(밤)", "file_name": "bg_citybridge_night.mp4" },
  { "description": "교통체증(낮)", "file_name": "bg_trafficjam_day.mp4" },
  { "description": "공항(낮)", "file_name": "bg_airport_day.mp4" },
  { "description": "고속도로 진입ic(낮)", "file_name": "bg_highwayentry_day.mp4" },
  { "description": "고속도로 주행(낮)", "file_name": "bg_highwaydrive_day.mp4" },
  { "description": "갯마을(낮)", "file_name": "bg_foreshore_day.mp4" },
  { "description": "자동세차장(낮)", "file_name": "bg_carwash_day1.mp4" },
  { "description": "힐링 풍경2", "file_name": "bg_healinglandscape2_day.mp4" },
  { "description": "힐링 풍경1", "file_name": "bg_healinglandscape1_day.mp4" },
  { "description": "하늘에서 젤리곰이 떨어져1", "file_name": "bg_fallingjellybear1_surreal.mp4" },
  { "description": "풍선을 타고 날아다님", "file_name": "bg_floatingballoons_surreal.mp4" },
  { "description": "초현실 세상(지브리풍 도시)", "file_name": "bg_ghiblicity_surreal.mp4" },
  { "description": "음료가 되서 보는 세상", "file_name": "bg_colorfuldrink_surreal.mp4" },
  { "description": "시골길(낮)", "file_name": "bg_countryroad_night.mp4" },
  { "description": "사탕으로 만들어진 세상2", "file_name": "bg_candywonderland2_surreal.mp4" },
  { "description": "공룡 정글 2", "file_name": "bg_jurassicjungle2_surreal.mp4" },
]